default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4

development:
  <<: *default
  host: localhost
  username: impthingsuser
  password: D0pP3|_G@|!ger
  database: impthingsdata

e2e_test:
  <<: *default
  host: localhost
  username: impthingse2e
  password: D|pP3|_G||!ger
  database: impthingstestdata

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:production_database, :host) %>
  username: <%= Rails.application.credentials.dig(:production_database, :username) %>
  password: <%= Rails.application.credentials.dig(:production_database, :password) %>
  database: <%= Rails.application.credentials.dig(:production_database, :database) %>
