default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  encoding: utf8mb4
  username: impthingsuser
  password: D0pP3|_G@|!ger
  database: impthingsdata

e2e_test:
  <<: *default
  host: localhost
  encoding: utf8mb4
  username: impthingse2e
  password: D|pP3|_G||!ger
  database: impthingstestdata
